sudo: required
dist: trusty
language: c
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libxcb-randr0-dev libconfig-dev libcairo2-dev libpango1.0-dev libxcb-ewmh-dev libxcb-icccm4-dev libasound2-dev
    - export CPPFLAGS=-DOLD_LIBCONFIG
script: make

